### ISSUE TITLE
要件と評価観点について

### ISSUE THREAD

**Issue by shqld** [CyberAgent/git-push-hackathon#10]
2つ質問があります。

1. ReactNativeは使っても良いでしょうか？

2. 評価観点1つ目の設計とは具体的に何を指すものでしょうか？

よろしくお願いします。

**Comment by shoheiyokoyama** [comment]
@shqld 

#### 1. `React Native`の使用について
`React Native`で実装されたアプリケーションでも歓迎は致しますが、今回は各プラットフォームに最適化されたアプリケーションを評価するという方針のため、受賞の対象外とさせて頂きます。ご了承下さい。

#### 2. 設計に関して
評価ポイントの「設計」に関してですが、参加者に創意工夫して考えて頂きたいので、具体的な評価項目は公開しない方針です。
しかし、最低限以下の項目は評価の一部になるかと思いますので、意識して頂きたいです。

・拡張性
・可読性
・非冗長性
