### ISSUE TITLE
結果発表について

### ISSUE THREAD

**Issue by kaelaela** [CyberAgent/git-push-hackathon#26]
発表は3/12(月)のお昼頃を予定しています。このレポジトリのissueを立てて発表します。
簡単な評価のポイントについても合わせて公開します。

みなさま、お疲れ様でした 😸

**Comment by shaunkawano** [comment]
### 結果発表時間変更のお知らせ

本日お昼頃を予定していました結果発表ですが、**15:00に発表とさせていただきます。** 発表方法についてはこちらのissueに記載のとおり、新規のissueを立てて発表します。

もう少々おまちください！

そして改めてみなさまお疲れ様でした！ 🐹
