### ISSUE TITLE
WebでOAuth認証のAPIを実行するときのCORSについて

### ISSUE THREAD

**Issue by Kusunoki-19** [CyberAgent/git-push-hackathon#31]
現在webコースで開発をしているのですが、OAuth認証の2段階目のPOSTをscript(XMLHttpRequest)から実行するときにCORSに引っかかってしまいます。(テストはChromeで実行しています)

error message : 
Failed to load https://github.com/login/oauth/access_token: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

(https://github.com/prose/gatekeeper に”GitHubのは、クライアント側のみのアプリケーションでのOAuthのWebアプリケーションフローを実装するのを防ぐことができます。”とありました)

(デバッグツールで見ると、POSTに対するResponseは帰ってきていてその中にはaccess_tokenも入っていました。しかしXMLHttpRequestはエラーになってしまいレスポンスを取得できていません。)

現在はHTMLだけを使ったformからPOSTすることでaccess_token(ファイル)のダウンロードをし、そのファイルに記載されているaccess_tokenを手動で入力しています。
しかし、評価するにしても、手動でファイルを開いて値を入力するのはどうなんだということで改善を考えました。

改善策としては、
①CORSにひっかからないブラウザ(Vivaldiとか)をしようする
②Gatekeeperを使用する(https://github.com/prose/gatekeeper)
③テスト用のサーバーも作成する
というものを模索しました。

しかし、①は実行環境が限られるので評価対象になるのかという疑問、②はそもそもの資料が少なく、もしかしたらサーバー側のプログラムかもしれないという疑問、③はvol.1のissueで「サーバーは必要ない」という回答がありサーバーは作らないほうが良いのかという疑問があります。

そのためwebコースでアプリケーションを作成する際は、HTMLフォームからファイルをダウンロードし手動で入力する、また、ChromeのF12デバッグツールでResponseを直接確認し手動入力するといった実装でも問題がないのか、それともwebコースはサーバーも構築したほうが良いのかお伺いしたく思っています。

ちなみに、access_tokenを用いて実行されるgist取得のAPIなどはクライアントサイドからの実行でも動作できています。

**Comment by RyotaSugawara** [comment]
@Kusunoki-19 

質問ありがとうございます 😄 

①に関してですが、アプリケーションとして最低限の機能が満たせていれば評価対象になります。評価対象とした上で実行環境が限られているという点を評価いたします。
②③に関しては実現手段の選択肢として各自工夫をしていただければと思います。

また③に関して、Vol.2では必要があればサーバーを準備していただいても構いません。

評価に関してですが、
設計と実装、アプリケーションとしての品質の良し悪しを評価軸としてしています。
上記評価軸をもとに各PullRequestで出されたアウトプットを評価いたします。

**Comment by Kusunoki-19** [comment]
@RyotaSugawara さん
ご回答ありがとうございました。
