### ISSUE TITLE
プロジェクトに含まれる生成物について

### ISSUE THREAD

**Issue by akkyie** [CyberAgent/git-push-hackathon#4]
ビルドができない場合は評価対象外とありますが、ツールにより生成されるファイルや依存関係など（iOSであればCocoaPodsによる`Pods`ディレクトリやCarthageによる`Carthage`ディレクトリなど）をプルリクエストに含める必要はありますか？
READMEやMakefile等にビルド手順を記載し審査の際に従ってもらうことは可能でしょうか。

関連して、自分のOAuthクライアントIDやクライアントシークレットをプルリクエストに含めたくない場合、審査の際に審査用のIDやシークレットを用いるなどの対応はありますか？

**Comment by ra1028** [comment]
依存パッケージやClient ID, Client Secretは、リポジトリに含める必要はありません。
評価のためのビルドに必要な依存解決などの工程は自身のフォルダにREADMEを作成し、工程を記載してください。
またClient ID, Client Secretも評価の際はこちらで用意したものを使用しますので、使用するべき箇所、またはファイル名をREADMEに記載してください。

今回の回答を![こちら](https://github.com/CyberAgent/git-push-hackathon#開発について)に記載させていただきました。
貴重なご意見ありがとうございました。

**Comment by akkyie** [comment]
@ra1028 承知しました。迅速なご回答ありがとうございます。

**Comment by massongit** [comment]
@ra1028 GItHub上に登録したAuthorization callback URLをアプリで用いる必要がある場合、Client IDやClient Secretと同様に、入力箇所をREADMEに記載すれば良いでしょうか？

**Comment by ra1028** [comment]
@massongit 

ありがとうございます。

Callback URLも含めたくない場合は、ご推察の通りREADMEに記載して頂ければ問題ありません。
よろしくお願いします。

**Comment by massongit** [comment]
@ra1028 回答ありがとうございました。
