### ISSUE TITLE
最低要件について質問です。

### ISSUE THREAD

**Issue by fumiya-kume** [CyberAgent/git-push-hackathon#42]
>最低要件
>GitHubのOAuthを用いたログインができる
>/gists APIを用いた機能がある
>gistの一覧表示ができる
>gistを投稿できる

最低要件の **gist の一覧表示ができる** 。というのは、「自分のGistが一覧表示される」という認識であってますか？

**Comment by RyotaSugawara** [comment]
@fumiya-kume 

質問ありがとうございます 😄 

自分のgistsでも特定のアカウントでもgistsの一覧が表示されていれば最低要件を満たしているものとします。

**Comment by fumiya-kume** [comment]
回答ありがとうございます
