### ISSUE TITLE
コピペの判断基準について

### ISSUE THREAD

**Issue by touyou** [CyberAgent/git-push-hackathon#5]
「コピペと思われるソースコード」というのはどのような基準、厳しさで判定されるのでしょうか？
例えば普段の開発からライブラリのように使っているユーティリティコード（ex. Swiftの便利extensionなど）を手でうつして組み込んだりすることや、設計やライブラリを使ったコーディングをするとき単純なためにサンプルコードと部分的に一致してしまうという場合もコピペと判断されてしまいますか？

**Comment by kaelaela** [comment]
@touyou 
あまり厳密に判定はしませんが、読んでいて不自然に感じるときはある程度検索し、似ていると思うコードを見つけたらdiffを確認する可能性はあります。不自然とは、他のコードと記述ルールが異なっている場合に感じることが多いです。ですから、

> 普段の開発からライブラリのように使っているユーティリティコード（ex. Swiftの便利extensionなど）

のように、自分で書いたコードはそうなりにくいと考えています。基本的に自分が書いたコードで、他人のコードのコピー出ない限り問題ありません。
また、扱う言語でよく使われる一般的な記述である場合もこれに該当しません。
(パッと見て、これ似てるな？や雰囲気が違うな？と感じないものなら特に気にしない方針です。👌)

**Comment by touyou** [comment]
@kaelaela ありがとうございます！
