### ISSUE TITLE
OAuth認証について

### ISSUE THREAD

**Issue by I3irth** [CyberAgent/git-push-hackathon#6]
OAuth認証に用いるサーバも、自分で作成したものを使用するという事ですか？

**Comment by shaunkawano** [comment]
@I3irth 

ありがとうございます。サーバーについてはご自身で用意する必要はなく、GitHubの提供するAPIを用いて認証処理を実装してください。

**Comment by I3irth** [comment]
回答ありがとうございます。了解しました！
