### ISSUE TITLE
最低要件に関して

### ISSUE THREAD

**Issue by massongit** [CyberAgent/git-push-hackathon#8]
最低要件の『[activity/feeds API](https://developer.github.com/v3/activity/feeds/)を用いたフィードの一覧表示』は、以下のいずれかを一覧表示できれば満たすという捉え方で良いでしょうか？
* GitHub global public timeline
* 特定のユーザーのpublic timeline (特定ユーザーの更新情報)
* 認証済みユーザーのpublic timeline (認証済みユーザーの更新情報)

**Comment by massongit** [comment]
『認証済みユーザーのprivate timeline』は[activity/feeds API](https://developer.github.com/v3/activity/feeds/)ではBasic認証の場合しか対応していないようなので、仮にこれを満たすことを最低条件としている場合、代わりに[activity/events API](https://developer.github.com/v3/activity/events/)の`GET /users/:username/received_events`を用いる形になるかと思います。

**Comment by kaelaela** [comment]
@massongit 

> • 認証済みユーザーのpublic timeline

こちらでお願いします。

**Comment by massongit** [comment]
ありがとうございます。

**Comment by shaunkawano** [comment]
@massongit 

前述にて、activity/feedsを用いることと、認証済みユーザーのpublic timeline (認証済みユーザーの更新情報)を表示する旨のお伝えをしましたが、訂正とさせて下さい。

> activity/events APIのList events that a user has receivedを用いる形になるかと思います。

こちらの解釈で問題ないです。

迷わせてしまい、申し訳ないです。
READMEのほうも合わせて修正します。

**Comment by shaunkawano** [comment]
READMEを修正しました: https://github.com/CyberAgent/git-push-hackathon/commit/d111b1873978460cd7cdfb1d4d2b19877cce4165

**Comment by massongit** [comment]
了解しました。

**Comment by massongit** [comment]
追加で質問ですが、activity/events APIで取得したイベントのうち、一部のイベントのみを対象に一覧表示した場合でも、最低要件は満たすのでしょうか？
