### ISSUE TITLE
最低要件について２

### ISSUE THREAD

**Issue by touyou** [CyberAgent/git-push-hackathon#9]
#8 で既に質問されていることでまだ不明な点が出てきたので質問です。
#8 ではあくまでactivity/feeds APIを用い、認証済みユーザのpublic timelineを使用するとのことでしたが実際にAPIを叩いてみると公式ドキュメントの例でいえば

```
{
  "timeline_url": "https://github.com/timeline",
  "user_url": "https://github.com/{user}",
  "current_user_public_url": "https://github.com/defunkt",
  "_links": {
    "timeline": {
      "href": "https://github.com/timeline",
      "type": "application/atom+xml"
    },
    "user": {
      "href": "https://github.com/{user}",
      "type": "application/atom+xml"
    },
    "current_user_public": {
      "href": "https://github.com/defunkt",
      "type": "application/atom+xml"
    }
  }
}
```

というようなJSONが返ってきます。これは自分のGitHub APIやURLリクエストに対する認識不足・知識不足であれば申し訳ないのですが、ドキュメントで「認証済みユーザーのpublic timeline」とされている `current_user_public_url`もしくは `links`の中の `current_user_public`は通常のユーザーページのURLのため、これにOAuthでとってきたアクセストークンをクエリーとして与えた `https://github.com/defunkt?access_token=ACCESS_TOKEN`からデータをとってきてもユーザーページのHTMLしか返ってきません。そのためREADMEにあるようなタイムラインの形式に変換するのが非常に困難なように思われます。

この件に関して最低要件は

- HTMLを頑張って解析してページ下のContribution Activityの部分のデータをタイムラインっぽく加工する
- なんらかの方法でこのURLをxmlとして取ってくる
- global public timelineであればXMLで取得できるのでそちらを表示する
- OAuth認証でJSONとしてタイムラインが返ってくるactivity/events APIのList events that a user has receivedを利用する

のいずれの意味で解釈すればよいでしょうか？

**Comment by shaunkawano** [comment]
@touyou 
ありがとうございます。

こちら、[README.mdの最低要件]の記述が誤りです。申し訳ないです。

> OAuth認証でJSONとしてタイムラインが返ってくるactivity/events APIのList events that a user has receivedを利用する

こちらの解釈で問題ないです。READMEの方も修正します。

**Comment by touyou** [comment]
@shaunkawano ありがとうございます！

**Comment by shaunkawano** [comment]
READMEを修正しました: https://github.com/CyberAgent/git-push-hackathon/commit/d111b1873978460cd7cdfb1d4d2b19877cce4165

**Comment by YokoMasa** [comment]
`current_user_public_url`のリスエストヘッダーに`Accept: application/atom+xml`を付ければxmlが帰って来ると思います！
<img width="960" alt="default" src="https://user-images.githubusercontent.com/24545564/35588090-772cb260-05b4-11e8-917e-a0fae249705d.png">
